import os
import shutil
import errno
import subprocess
import uuid
#from vboxapi import VirtualBoxManager
#from virtualbox.library import VBoxErrorObjectNotFound
#import pywintypes
#import win32com

__author__ = 'admin'

"""
environment variable path -> add C:\Program Files\Oracle\VirtualBox;
"""

class MachineCreator :
    machineName = "android_x86"
    VmRoot = "C:/Users/Owner/VirtualBox Vms" #server vm folder path
    VmRootWin = "C:\\Users\\Owner\\VirtualBox VMs"
    machineNumber = 1
    portNumber = 1100
    nUUID = ""
    machUUID = ""

    def __init__(self) :
        #self.mgr = VirtualBoxManager(None,None)
        #self.vbox = self.mgr.vbox
        #self.userName = userName
        return

    def createNewMachine(self) :
        self.setMachineNumber()
        self.cpyMachine()
        self.setNewUUID()
        self.setXml()
        self.registerVm()
        return

    def setMachineNumber(self) :
        while True:
            if os.path.isdir(self.VmRoot + "/android_x86_" + str(self.machineNumber)):
                self.machineNumber += 1
            else:
                break
        self.portNumber += self.machineNumber
        print "Machine numeber : " + str(self.machineNumber)
        print "Port numeber :    " + str(self.portNumber)
        return

    def cpyMachine(self) :
        mNumb = str(self.machineNumber)
        src = self.VmRoot + "/android_x86_"
        dst = self.VmRoot + "/android_x86_" + mNumb
        try:
            shutil.copytree(src, dst)
        except OSError as exc:
            if exc.errno == errno.ENOTDIR:
                shutil.copy(src, dst)
            else: raise
        os.rename(dst+"/android_x86_.vbox",dst+"/android_x86_"+ mNumb +".vbox")
        os.rename(dst+"/android_x86_.vbox-prev",dst+"/android_x86_"+ mNumb +".vbox-prev")
        os.rename(dst+"/android_x86_.vdi",dst+"/android_x86_"+ mNumb +".vdi")
        return

    def setNewUUID(self) :
        mNumb = str(self.machineNumber)
        pipe = subprocess.Popen("VBoxManage internalcommands sethduuid \"" + self.VmRootWin + "\\android_x86_" + mNumb + "\\android_x86_" + mNumb + ".vdi",
                                shell = True,
                                stdin = subprocess.PIPE,
                                stdout = subprocess.PIPE,
                                stderr = subprocess.PIPE)
        pipe.stdin.close()
        stdout, stderr = pipe.communicate()

        self.nUUID = stdout[17:-2]
        self.machUUID = uuid.uuid4()

        print stderr
        print "new HD UUID :        " , self.nUUID
        print "new Machine UUID :   " , self.machUUID
        print "\n"
        return

    def setXml(self) :
        mNumb = str(self.machineNumber)
        xmlString = "<?xml version=\"1.0\"?>\n"
        xmlString += "<!--\n"
        xmlString += "** DO NOT EDIT THIS FILE.\n"
        xmlString += "** If you make changes to this file while any VirtualBox related application\n"
        xmlString += "** is running, your changes will be overwritten later, without taking effect.\n"
        xmlString += "** Use VBoxManage or the VirtualBox Manager GUI to make changes.\n"
        xmlString += "-->\n"
        xmlString += "<VirtualBox xmlns=\"http://www.innotek.de/VirtualBox-settings\" version=\"1.14-windows\">\n"
        xmlString += "  <Machine uuid=\"{" + str(self.machUUID)
        xmlString +=     "}\" name=\"android_x86_" + mNumb
        xmlString +=     "\" OSType=\"Linux\" snapshotFolder=\"Snapshots\" lastStateChange=\"2015-09-12T11:35:36Z\">\n"
        xmlString += "    <MediaRegistry>\n"
        xmlString += "      <HardDisks>\n"
        xmlString += "        <HardDisk uuid=\"{" + self.nUUID + "}\" location=\"android_x86_" + mNumb + ".vdi\" format=\"VDI\" type=\"Normal\"/>\n"
        xmlString += "      </HardDisks>\n"
        xmlString += "      <DVDImages/>\n"
        xmlString += "      <FloppyImages/>\n"
        xmlString += "    </MediaRegistry>\n"
        xmlString += "    <ExtraData>\n"
        xmlString += "      <ExtraDataItem name=\"CustomVideoMode1\" value=\"320x480x16\"/>\n"
        xmlString += "      <ExtraDataItem name=\"GUI/LastCloseAction\" value=\"PowerOff\"/>\n"
        xmlString += "      <ExtraDataItem name=\"GUI/LastGuestSizeHint\" value=\"320,480\"/>\n"
        xmlString += "      <ExtraDataItem name=\"GUI/LastNormalWindowPosition\" value=\"410,152,320,522\"/>\n"
        xmlString += "    </ExtraData>\n"
        xmlString += "    <Hardware version=\"2\">\n"
        xmlString += "      <CPU count=\"1\" hotplug=\"false\">\n"
        xmlString += "        <HardwareVirtEx enabled=\"true\"/>\n"
        xmlString += "        <HardwareVirtExNestedPaging enabled=\"true\"/>\n"
        xmlString += "        <HardwareVirtExVPID enabled=\"true\"/>\n"
        xmlString += "        <HardwareVirtExUX enabled=\"true\"/>\n"
        xmlString += "        <PAE enabled=\"false\"/>\n"
        xmlString += "        <LongMode enabled=\"false\"/>\n"
        xmlString += "        <HardwareVirtExLargePages enabled=\"false\"/>\n"
        xmlString += "        <HardwareVirtForce enabled=\"false\"/>\n"
        xmlString += "      </CPU>\n"
        xmlString += "      <Memory RAMSize=\"256\" PageFusion=\"false\"/>\n"
        xmlString += "      <HID Pointing=\"USBTablet\" Keyboard=\"PS2Keyboard\"/>\n"
        xmlString += "      <HPET enabled=\"false\"/>\n"
        xmlString += "      <Chipset type=\"PIIX3\"/>\n"
        xmlString += "      <Boot>\n"
        xmlString += "        <Order position=\"1\" device=\"Floppy\"/>\n"
        xmlString += "        <Order position=\"2\" device=\"DVD\"/>\n"
        xmlString += "        <Order position=\"3\" device=\"HardDisk\"/>\n"
        xmlString += "        <Order position=\"4\" device=\"None\"/>\n"
        xmlString += "      </Boot>\n"
        xmlString += "      <Display VRAMSize=\"12\" monitorCount=\"1\" accelerate3D=\"false\" accelerate2DVideo=\"false\"/>\n"
        xmlString += "      <VideoCapture enabled=\"false\" screens=\"18446744073709551615\" horzRes=\"1024\" vertRes=\"768\" rate=\"512\" fps=\"25\"/>\n"
        xmlString += "      <RemoteDisplay enabled=\"false\" authType=\"Null\" authTimeout=\"5000\"/>\n"
        xmlString += "      <BIOS>\n"
        xmlString += "        <ACPI enabled=\"true\"/>\n"
        xmlString += "        <IOAPIC enabled=\"false\"/>\n"
        xmlString += "        <Logo fadeIn=\"true\" fadeOut=\"true\" displayTime=\"0\"/>\n"
        xmlString += "        <BootMenu mode=\"MessageAndMenu\"/>\n"
        xmlString += "        <TimeOffset value=\"0\"/>\n"
        xmlString += "        <PXEDebug enabled=\"false\"/>\n"
        xmlString += "      </BIOS>\n"
        xmlString += "      <USB>\n"
        xmlString += "        <Controllers>\n"
        xmlString += "          <Controller name=\"OHCI\" type=\"OHCI\"/>\n"
        xmlString += "        </Controllers>\n"
        xmlString += "        <DeviceFilters/>\n"
        xmlString += "      </USB>\n"
        xmlString += "      <Network>\n"
        xmlString += "        <Adapter slot=\"0\" enabled=\"true\" MACAddress=\"080027607CAB\" cable=\"true\" speed=\"0\" type=\"Am79C973\">\n"
        xmlString += "          <DisabledModes>\n"
        xmlString += "            <InternalNetwork name=\"intnet\"/>\n"
        xmlString += "            <NATNetwork name=\"NatNetwork\"/>\n"
        xmlString += "          </DisabledModes>\n"
        xmlString += "          <NAT>\n"
        xmlString += "            <DNS pass-domain=\"true\" use-proxy=\"false\" use-host-resolver=\"false\"/>\n"
        xmlString += "            <Alias logging=\"false\" proxy-only=\"false\" use-same-ports=\"false\"/>\n"
        xmlString += "            <Forwarding name=\"Rule 1\" proto=\"1\" hostport=\"" + str(self.portNumber) + "\" guestport=\"" + str(self.portNumber) + "\"/>\n"
        xmlString += "          </NAT>\n"
        xmlString += "        </Adapter>\n"
        xmlString += "        <Adapter slot=\"1\" enabled=\"false\" MACAddress=\"0800271E4243\" cable=\"true\" speed=\"0\" type=\"Am79C973\">\n"
        xmlString += "          <DisabledModes>\n"
        xmlString += "            <NAT>\n"
        xmlString += "              <DNS pass-domain=\"true\" use-proxy=\"false\" use-host-resolver=\"false\"/>\n"
        xmlString += "              <Alias logging=\"false\" proxy-only=\"false\" use-same-ports=\"false\"/>\n"
        xmlString += "            </NAT>\n"
        xmlString += "          </DisabledModes>\n"
        xmlString += "        </Adapter>\n"
        xmlString += "        <Adapter slot=\"2\" enabled=\"false\" MACAddress=\"0800279A565C\" cable=\"true\" speed=\"0\" type=\"Am79C973\">\n"
        xmlString += "          <DisabledModes>\n"
        xmlString += "            <NAT>\n"
        xmlString += "              <DNS pass-domain=\"true\" use-proxy=\"false\" use-host-resolver=\"false\"/>\n"
        xmlString += "              <Alias logging=\"false\" proxy-only=\"false\" use-same-ports=\"false\"/>\n"
        xmlString += "            </NAT>\n"
        xmlString += "          </DisabledModes>\n"
        xmlString += "        </Adapter>\n"
        xmlString += "        <Adapter slot=\"3\" enabled=\"false\" MACAddress=\"080027301499\" cable=\"true\" speed=\"0\" type=\"Am79C973\">\n"
        xmlString += "          <DisabledModes>\n"
        xmlString += "            <NAT>\n"
        xmlString += "              <DNS pass-domain=\"true\" use-proxy=\"false\" use-host-resolver=\"false\"/>\n"
        xmlString += "              <Alias logging=\"false\" proxy-only=\"false\" use-same-ports=\"false\"/>\n"
        xmlString += "            </NAT>\n"
        xmlString += "          </DisabledModes>\n"
        xmlString += "        </Adapter>\n"
        xmlString += "        <Adapter slot=\"4\" enabled=\"false\" MACAddress=\"080027E58BB4\" cable=\"true\" speed=\"0\" type=\"Am79C973\">\n"
        xmlString += "          <DisabledModes>\n"
        xmlString += "            <NAT>\n"
        xmlString += "              <DNS pass-domain=\"true\" use-proxy=\"false\" use-host-resolver=\"false\"/>\n"
        xmlString += "              <Alias logging=\"false\" proxy-only=\"false\" use-same-ports=\"false\"/>\n"
        xmlString += "            </NAT>\n"
        xmlString += "          </DisabledModes>\n"
        xmlString += "        </Adapter>\n"
        xmlString += "        <Adapter slot=\"5\" enabled=\"false\" MACAddress=\"0800272D0BC2\" cable=\"true\" speed=\"0\" type=\"Am79C973\">\n"
        xmlString += "          <DisabledModes>\n"
        xmlString += "            <NAT>\n"
        xmlString += "              <DNS pass-domain=\"true\" use-proxy=\"false\" use-host-resolver=\"false\"/>\n"
        xmlString += "              <Alias logging=\"false\" proxy-only=\"false\" use-same-ports=\"false\"/>\n"
        xmlString += "            </NAT>\n"
        xmlString += "          </DisabledModes>\n"
        xmlString += "        </Adapter>\n"
        xmlString += "        <Adapter slot=\"6\" enabled=\"false\" MACAddress=\"0800274744D0\" cable=\"true\" speed=\"0\" type=\"Am79C973\">\n"
        xmlString += "          <DisabledModes>\n"
        xmlString += "            <NAT>\n"
        xmlString += "              <DNS pass-domain=\"true\" use-proxy=\"false\" use-host-resolver=\"false\"/>\n"
        xmlString += "              <Alias logging=\"false\" proxy-only=\"false\" use-same-ports=\"false\"/>\n"
        xmlString += "            </NAT>\n"
        xmlString += "          </DisabledModes>\n"
        xmlString += "        </Adapter>\n"
        xmlString += "        <Adapter slot=\"7\" enabled=\"false\" MACAddress=\"080027B7131D\" cable=\"true\" speed=\"0\" type=\"Am79C973\">\n"
        xmlString += "          <DisabledModes>\n"
        xmlString += "            <NAT>\n"
        xmlString += "              <DNS pass-domain=\"true\" use-proxy=\"false\" use-host-resolver=\"false\"/>\n"
        xmlString += "              <Alias logging=\"false\" proxy-only=\"false\" use-same-ports=\"false\"/>\n"
        xmlString += "            </NAT>\n"
        xmlString += "          </DisabledModes>\n"
        xmlString += "        </Adapter>\n"
        xmlString += "      </Network>\n"
        xmlString += "      <UART>\n"
        xmlString += "        <Port slot=\"0\" enabled=\"false\" IOBase=\"0x3f8\" IRQ=\"4\" hostMode=\"Disconnected\"/>\n"
        xmlString += "        <Port slot=\"1\" enabled=\"false\" IOBase=\"0x2f8\" IRQ=\"3\" hostMode=\"Disconnected\"/>\n"
        xmlString += "      </UART>\n"
        xmlString += "      <LPT>\n"
        xmlString += "        <Port slot=\"0\" enabled=\"false\" IOBase=\"0x378\" IRQ=\"7\"/>\n"
        xmlString += "        <Port slot=\"1\" enabled=\"false\" IOBase=\"0x378\" IRQ=\"7\"/>\n"
        xmlString += "      </LPT>\n"
        xmlString += "      <AudioAdapter controller=\"AC97\" driver=\"DirectSound\" enabled=\"true\"/>\n"
        xmlString += "      <RTC localOrUTC=\"UTC\"/>\n"
        xmlString += "      <SharedFolders/>\n"
        xmlString += "      <Clipboard mode=\"Disabled\"/>\n"
        xmlString += "      <DragAndDrop mode=\"Disabled\"/>\n"
        xmlString += "      <IO>\n"
        xmlString += "        <IoCache enabled=\"true\" size=\"5\"/>\n"
        xmlString += "        <BandwidthGroups/>\n"
        xmlString += "      </IO>\n"
        xmlString += "      <HostPci>\n"
        xmlString += "        <Devices/>\n"
        xmlString += "      </HostPci>\n"
        xmlString += "      <EmulatedUSB>\n"
        xmlString += "        <CardReader enabled=\"false\"/>\n"
        xmlString += "      </EmulatedUSB>\n"
        xmlString += "      <Guest memoryBalloonSize=\"0\"/>\n"
        xmlString += "      <GuestProperties>\n"
        xmlString += "        <GuestProperty name=\"/VirtualBox/HostInfo/GUI/LanguageID\" value=\"ko_KR\" timestamp=\"1442057727742047200\" flags=\"\"/>\n"
        xmlString += "      </GuestProperties>\n"
        xmlString += "    </Hardware>\n"
        xmlString += "    <StorageControllers>\n"
        xmlString += "      <StorageController name=\"IDE\" type=\"PIIX4\" PortCount=\"2\" useHostIOCache=\"true\" Bootable=\"true\">\n"
        xmlString += "        <AttachedDevice type=\"HardDisk\" port=\"0\" device=\"0\">\n"
        xmlString += "          <Image uuid=\"{" + self.nUUID + "}\"/>\n"
        xmlString += "        </AttachedDevice>\n"
        xmlString += "        <AttachedDevice passthrough=\"false\" type=\"DVD\" port=\"1\" device=\"0\"/>\n"
        xmlString += "      </StorageController>\n"
        xmlString += "    </StorageControllers>\n"
        xmlString += "  </Machine>\n"
        xmlString += "</VirtualBox>"

        f = open(self.VmRoot + "/android_x86_" + mNumb + "/android_x86_"+ mNumb +".vbox","w")
        f.write(xmlString)
        f.close
        return

    def registerVm(self) :
        mNumb = str(self.machineNumber)
        pipe = subprocess.Popen("VBoxManage registervm \"" + self.VmRootWin + "\\android_x86_" + mNumb + "\\android_x86_" + mNumb + ".vbox",
                                shell = True,
                                stdin = subprocess.PIPE,
                                stdout = subprocess.PIPE,
                                stderr = subprocess.PIPE)
        pipe.stdin.close()
        stdout, stderr = pipe.communicate()

        if stderr :
            print stderr
            print "Create failed"
        else :
            print "Create done"
        return